### ISSUE TITLE
css in repo doesn't match deployed version

### ISSUE THREAD

**Issue by brycekahle** [blahblahblah-/goodservice#8]
I wanted to submit a PR to fix some CSS, but it seems what is deployed does not match what is in the repo, specifically: https://github.com/blahblahblah-/goodservice/blob/master/app/assets/stylesheets/index.scss

Perhaps you need to push some commits? 😄

**Comment by sunny-ng** [comment]
The commits are up to date, but...

Some of the CSS is also here:
https://github.com/blahblahblah-/goodservice/blob/master/app/javascript/packs/goodserviceApp/assets/stylesheets/app.scss

And there's quite a bit of inline CSS used in the React components. 🙈 

Yes, the CSS is really messy, I know, I know. 😱

**Comment by brycekahle** [comment]
Ahhhhh. That makes more sense. Thanks!
